package oe.qmc;

import oe.Log;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class MinecraftQMC extends QMC {
  public static void load() {
    
    int r = length();
    
    add(Block.cobblestone, 1);
    add(Block.stone, 1);
    add(Block.dirt, 1);
    add(Block.gravel, 1);
    add(Block.grass, 1);
    add(Block.mycelium, 8);
    add(Block.sand, 1);
    add(Item.diamond, 8192);
    add(Item.ingotGold, 2048);
    add(Item.ingotIron, 256);
    add(Block.sapling, 8);
    add(Block.leaves, 1);
    add(Block.wood, 32);
    add(Item.dyePowder, 4, 512);
    add(Item.dyePowder, 8);
    add(Block.plantRed, 8);
    add(Block.plantYellow, 8);
    add(Item.glowstone, 64);
    add(Item.slimeBall, 64);
    add(Item.clay, 32);
    add(Block.web, 8);
    add(Block.tallGrass, 8);
    add(Block.deadBush, 8);
    add(Block.mushroomBrown, 4);
    add(Block.mushroomRed, 4);
    add(Block.cloth, 48); // Wool
    add(Item.gunpowder, 256);
    add(Item.coal, 0, 128); // Coal
    add(Item.coal, 1, 32); // Charcoal
    add(Block.cobblestoneMossy, 128);
    add(Item.leather, 12);
    add(Block.reed, 16);
    add(Item.reed, 16);
    add(Item.wheat, 24);
    add(Item.carrot, 24);
    add(Item.potato, 24);
    add(Item.poisonousPotato, 12);
    add(Item.bakedPotato, 24);
    add(Block.carrot, 12);
    add(Block.potato, 12);
    add(Block.obsidian, 128);
    add(Item.redstone, 64);
    add(Item.snowball, 1);
    add(Block.ice, 16);
    add(Block.cactus, 8);
    add(Item.clay, 8);
    add(Block.pumpkin, 64);
    add(Item.pumpkinSeeds, 16);
    add(Item.melon, 12);
    add(Block.melon, 108);
    add(Block.netherrack, 1);
    add(Block.slowSand, 4);
    add(Item.glowstone, 64);
    add(Item.egg, 32);
    add(Block.vine, 16);
    add(Block.waterlily, 16);
    add(Block.netherBrick, 4);
    add(Block.netherStalk, 32);
    add(Block.whiteStone, 8);
    add(Item.enderPearl, 1024);
    add(Item.blazeRod, 512);
    add(Item.emerald, 16384);
    add(Item.netherQuartz, 512);
    add(Block.cocoaPlant, 24);
    add(Item.flint, 1);
    add(Item.feather, 12);
    add(Item.chickenRaw, 12);
    add(Item.feather, 12);
    add(Item.beefRaw, 32);
    add(Item.porkRaw, 32);
    add(Item.bone, 12);
    add(Item.rottenFlesh, 12);
    add(Item.ghastTear, 2048);
    add(Item.spiderEye, 12);
    add(Item.fishRaw, 32);
    
    add(Block.planks, getQMC(Block.wood) / 4);
    add(Item.stick, getQMC(Block.planks) / 2);
    add(Block.glass, getQMC(Block.sand));
    add(Block.blockIron, getQMC(Item.ingotIron) * 9);
    add(Block.blockGold, getQMC(Item.ingotGold) * 9);
    add(Block.blockDiamond, getQMC(Item.diamond) * 9);
    add(Block.blockLapis, getQMC(new ItemStack(Item.dyePowder, 1, 4)) * 9);
    add(Block.blockEmerald, getQMC(Item.emerald) * 9);
    add(Block.blockNetherQuartz, getQMC(Item.netherQuartz) * 9);
    add(Block.blockRedstone, getQMC(Item.redstone) * 9);
    add(Item.netherStar, getQMC(Item.diamond) * 64);
    add(Item.brick, getQMC(Item.clay));
    add(Block.coalBlock, getQMC(Item.coal) * 9);
    add(Block.tripWire, getQMC(Block.cloth) / 4);
    add(Item.bow, (getQMC(Item.stick) * 3) + (getQMC(Block.tripWire) * 3));
    add(Block.dispenser, (getQMC(Block.cobblestone) * 7) + getQMC(Item.bow) + getQMC(Item.redstone));
    add(Block.torchRedstoneActive, getQMC(Item.stick) + getQMC(Item.redstone));
    add(Block.torchRedstoneIdle, getQMC(Block.torchRedstoneActive));
    add(Block.railPowered, ((getQMC(Item.ingotGold) * 6) + getQMC(Item.redstone) + getQMC(Item.stick)) / 6);
    add(Block.railDetector, ((getQMC(Item.ingotGold) * 6) + getQMC(Item.redstone) + getQMC(Block.pressurePlateStone)) / 6);
    add(Block.rail, ((getQMC(Item.ingotIron) * 6) + getQMC(Item.stick)) / 16);
    add(Block.railActivator, ((getQMC(Item.ingotIron) * 6) + getQMC(Block.torchRedstoneActive) + ((getQMC(Item.stick) * 2))) / 6);
    add(Block.pistonBase, (getQMC(Block.wood) * 3) + (getQMC(Block.cobblestone) * 4) + getQMC(Item.ingotIron) + getQMC(Item.redstone));
    add(Block.pistonStickyBase, getQMC(Block.pistonBase) + getQMC(Item.slimeBall));
    add(Block.brick, getQMC(Item.brick) * 4);
    add(Block.sandStone, getQMC(Block.sand) * 4);
    add(Block.music, (getQMC(Block.wood) * 8) + getQMC(Item.redstone));
    add(Block.tnt, (getQMC(Block.sand) * 4) + (getQMC(Item.gunpowder) * 5));
    add(Block.torchWood, (getQMC(Item.stick) + getQMC(new ItemStack(Item.coal, 1, 1))) / 4);
    add(Item.bed, (getQMC(Block.wood) * 3) + (getQMC(Block.cloth) * 3));
    add(Item.blazePowder, getQMC(Item.blazeRod) / 5);
    add(Item.magmaCream, getQMC(Item.blazePowder) + getQMC(Item.slimeBall));
    add(Item.chickenCooked, getQMC(Item.chickenRaw));
    add(Item.beefCooked, getQMC(Item.beefRaw));
    add(Item.porkCooked, getQMC(Item.porkRaw));
    add(Item.fishCooked, getQMC(Item.fishRaw));
    add(Item.bread, getQMC(Item.wheat) * 3);
    add(Item.seeds, getQMC(Item.wheat));
    add(Item.sugar, getQMC(Item.reed));
    add(Item.paper, getQMC(Item.reed));
    add(Item.book, (getQMC(Item.paper) * 3) + getQMC(Item.leather));
    add(Block.bookShelf, (getQMC(Item.book) * 3) + (getQMC(Block.wood) * 6));
    add(Block.stairsWoodBirch, (getQMC(Block.wood) * 6) / 4);
    add(Block.stairsWoodJungle, (getQMC(Block.wood) * 6) / 4);
    add(Block.stairsWoodOak, (getQMC(Block.wood) * 6) / 4);
    add(Block.stairsWoodSpruce, (getQMC(Block.wood) * 6) / 4);
    add(Block.chest, getQMC(Block.wood) * 8);
    add(Block.workbench, getQMC(Block.wood) * 4);
    add(Block.furnaceIdle, getQMC(Block.cobblestone) * 8);
    add(Block.signPost, ((getQMC(Block.wood) * 6) + getQMC(Item.stick)) / 3);
    add(Block.signWall, getQMC(Block.signPost));
    add(Item.sign, getQMC(Block.signPost));
    add(Block.doorWood, getQMC(Block.wood) * 6);
    add(Item.doorWood, getQMC(Block.wood) * 6);
    add(Block.doorIron, getQMC(Item.ingotIron) * 6);
    add(Item.doorIron, getQMC(Item.ingotIron) * 6);
    add(Block.ladder, (getQMC(Item.stick) * 6) / 2);
    add(Block.lever, getQMC(Item.stick) + getQMC(Block.cobblestone));
    add(Block.pressurePlateStone, getQMC(Block.stone) * 2);
    add(Block.pressurePlatePlanks, getQMC(Block.planks) * 2);
    add(Block.stoneButton, getQMC(Block.cobblestone) * 2);
    add(Block.woodenButton, getQMC(Block.planks) * 2);
    add(Block.snow, getQMC(Item.snowball) * 4);
    add(Block.blockClay, getQMC(Item.clay) * 4);
    add(Block.jukebox, (getQMC(Block.planks) * 8) + getQMC(Item.redstone));
    add(Block.fence, (getQMC(Item.stick) * 6) / 2);
    add(Block.glowStone, getQMC(Item.glowstone) * 4);
    add(Item.bucketEmpty, getQMC(Item.ingotIron) * 3);
    add(Item.bucketMilk, (getQMC(Item.ingotIron) * 3) + 32);
    add(Item.bucketWater, (getQMC(Item.ingotIron) * 3) + 2);
    add(Item.bucketLava, (getQMC(Item.ingotIron) * 3) + 16);
    add(Block.cake, ((getQMC(Item.bucketMilk) - getQMC(Item.bucketEmpty)) * 3) + ((getQMC(Item.sugar) * 2) + getQMC(Item.egg)) + (getQMC(Item.wheat) * 3));
    add(Item.cake, getQMC(Block.cake));
    add(Item.redstoneRepeater, (getQMC(Block.torchRedstoneActive) * 2) + getQMC(Item.redstone) + (getQMC(Block.stone) * 3));
    add(Block.redstoneRepeaterActive, getQMC(Item.redstoneRepeater));
    add(Block.redstoneRepeaterIdle, getQMC(Item.redstoneRepeater));
    add(Block.tripWireSource, getQMC(Item.ingotIron) + getQMC(Item.stick) + getQMC(Block.planks));
    add(Block.chestTrapped, getQMC(Block.chest) + getQMC(Block.tripWireSource));
    add(Block.trapdoor, getQMC(Block.planks) * 6 / 2);
    add(Block.stoneBrick, getQMC(Block.stone) * 4);
    add(Block.fenceIron, getQMC(Item.ingotIron) * 6 / 16);
    add(Block.thinGlass, getQMC(Block.glass) * 6 / 16);
    add(Block.fenceGate, (getQMC(Block.planks) * 2) + (getQMC(Item.stick) * 4));
    add(Block.stairsBrick, getQMC(Block.brick) * 6 / 4);
    add(Block.stairsStoneBrick, getQMC(Block.stoneBrick) * 6 / 4);
    add(Block.stairsNetherQuartz, getQMC(Block.blockNetherQuartz) * 6 / 4);
    add(Block.stairsCobblestone, getQMC(Block.cobblestone) * 6 / 4);
    add(Block.netherFence, getQMC(Block.netherBrick) * 6 / 6);
    add(Block.stairsNetherBrick, getQMC(Block.netherBrick) * 6 / 4);
    add(Block.enchantmentTable, (getQMC(Block.obsidian) * 4) + (getQMC(Item.diamond) * 4) + getQMC(Item.book));
    add(Block.cauldron, getQMC(Item.ingotIron) * 7);
    add(Block.redstoneLampActive, getQMC(Block.glowStone) + (getQMC(Item.redstone) * 4));
    add(Block.redstoneLampIdle, getQMC(Block.redstoneLampActive));
    add(Block.woodSingleSlab, getQMC(Block.planks) * 3 / 6);
    add(Block.woodDoubleSlab, getQMC(Block.woodSingleSlab) * 2);
    add(Block.stoneSingleSlab, 0, getQMC(Block.stone) * 3 / 6);
    add(Block.stoneDoubleSlab, 0, getQMC(new ItemStack(Block.stoneDoubleSlab, 1, 0)) * 2);
    add(Block.stoneSingleSlab, 1, getQMC(Block.sandStone) * 3 / 6);
    add(Block.stoneDoubleSlab, 1, getQMC(new ItemStack(Block.stoneDoubleSlab, 1, 1)) * 2);
    add(Block.stoneSingleSlab, 3, getQMC(Block.cobblestone) * 3 / 6);
    add(Block.stoneDoubleSlab, 3, getQMC(new ItemStack(Block.stoneDoubleSlab, 1, 3)) * 2);
    add(Block.stoneSingleSlab, 4, getQMC(Block.brick) * 3 / 6);
    add(Block.stoneDoubleSlab, 4, getQMC(new ItemStack(Block.stoneDoubleSlab, 1, 4)) * 2);
    add(Block.stoneSingleSlab, 5, getQMC(Block.stoneBrick) * 3 / 6);
    add(Block.stoneDoubleSlab, 5, getQMC(new ItemStack(Block.stoneDoubleSlab, 1, 5)) * 2);
    add(Block.stoneSingleSlab, 6, getQMC(Block.netherBrick) * 3 / 6);
    add(Block.stoneDoubleSlab, 6, getQMC(new ItemStack(Block.stoneDoubleSlab, 1, 6)) * 2);
    add(Block.stoneSingleSlab, 7, getQMC(Block.blockNetherQuartz) * 3 / 6);
    add(Block.stoneDoubleSlab, 7, getQMC(new ItemStack(Block.stoneDoubleSlab, 1, 7)) * 2);
    add(Item.eyeOfEnder, getQMC(Item.enderPearl) + getQMC(Item.blazePowder));
    add(Block.enderChest, (getQMC(Block.obsidian) * 8) + getQMC(Item.eyeOfEnder));
    add(Block.beacon, (getQMC(Block.obsidian) * 3) + (getQMC(Block.glass) * 5) + getQMC(Item.netherStar));
    add(Block.cobblestoneWall, 0, getQMC(Block.cobblestone) * 6 / 6);
    add(Block.cobblestoneWall, 1, getQMC(Block.cobblestoneMossy) * 6 / 6);
    add(Block.flowerPot, getQMC(Item.brick) * 3);
    add(Block.anvil, (getQMC(Block.blockIron) * 3) + (getQMC(Item.ingotIron) * 4));
    add(Block.pressurePlateGold, getQMC(Item.ingotGold) * 2);
    add(Block.pressurePlateIron, getQMC(Item.ingotIron) * 2);
    add(Block.redstoneComparatorActive, (getQMC(Block.stone) * 3) + (getQMC(Block.torchRedstoneActive) * 3) + getQMC(Item.netherQuartz));
    add(Block.redstoneComparatorIdle, getQMC(Block.redstoneComparatorActive));
    add(Item.comparator, getQMC(Block.redstoneComparatorActive));
    add(Block.hopperBlock, (getQMC(Item.ingotIron) * 5) + getQMC(Block.chest));
    add(Block.dropper, (getQMC(Block.cobblestone) * 7) + getQMC(Item.redstone));
    add(Block.hardenedClay, getQMC(Block.blockClay));
    add(Block.stainedClay, ((getQMC(Block.hardenedClay) * 8) + getQMC(Item.dyePowder)) / 8);
    add(Block.carpet, getQMC(Block.cloth) * 2 / 3);
    add(Item.axeDiamond, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.diamond) * 3));
    add(Item.pickaxeDiamond, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.diamond) * 3));
    add(Item.shovelDiamond, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.diamond) * 1));
    add(Item.swordDiamond, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.diamond) * 2));
    add(Item.axeGold, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.ingotGold) * 3));
    add(Item.pickaxeGold, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.ingotGold) * 3));
    add(Item.shovelGold, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.ingotGold) * 1));
    add(Item.swordGold, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.ingotGold) * 2));
    add(Item.axeIron, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.ingotIron) * 3));
    add(Item.pickaxeIron, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.ingotIron) * 3));
    add(Item.shovelIron, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.ingotIron) * 1));
    add(Item.swordIron, 0, (getQMC(Item.stick) * 2) + (getQMC(Item.ingotIron) * 2));
    add(Item.axeStone, 0, (getQMC(Item.stick) * 2) + (getQMC(Block.cobblestone) * 3));
    add(Item.pickaxeStone, 0, (getQMC(Item.stick) * 2) + (getQMC(Block.cobblestone) * 3));
    add(Item.shovelStone, 0, (getQMC(Item.stick) * 2) + (getQMC(Block.cobblestone) * 1));
    add(Item.swordStone, 0, (getQMC(Item.stick) * 2) + (getQMC(Block.cobblestone) * 2));
    add(Item.bowlEmpty, getQMC(Block.wood) * 3 / 4);
    add(Item.bowlEmpty, getQMC(Item.bowlEmpty) + 16);
    add(Item.arrow, (getQMC(Item.stick) + getQMC(Item.flint) + getQMC(Item.feather)) / 4);
    add(Item.boat, getQMC(Block.wood) * 5);
    add(Item.minecartEmpty, getQMC(Item.ingotIron) * 5);
    add(Item.minecartCrate, getQMC(Item.minecartEmpty) + getQMC(Block.chest));
    add(Item.minecartPowered, getQMC(Item.minecartEmpty) + getQMC(Block.furnaceIdle));
    add(Item.minecartHopper, getQMC(Item.minecartEmpty) + getQMC(Block.hopperBlock));
    add(Item.minecartTnt, getQMC(Item.minecartEmpty) + getQMC(Block.tnt));
    add(Item.compass, getQMC(Item.redstone) + (getQMC(Item.ingotIron) * 4));
    add(Item.fishingRod, 0, (getQMC(Item.stick) * 3) + (getQMC(Block.tripWire) * 2));
    add(Item.pocketSundial, (getQMC(Item.ingotGold) * 4) + getQMC(Item.redstone));
    add(Item.cookie, ((getQMC(Item.wheat) * 2) + getQMC(Block.cocoaPlant)) / 8);
    add(Item.map, (getQMC(Item.paper) * 8) + getQMC(Item.compass));
    add(Item.glassBottle, getQMC(Block.glass) * 3 / 3);
    add(Item.fermentedSpiderEye, getQMC(Block.mushroomBrown) + getQMC(Item.sugar) + getQMC(Item.spiderEye));
    add(Item.speckledMelon, (getQMC(Item.goldNugget) * 8) + getQMC(Item.melon));
    add(Item.pumpkinPie, getQMC(Item.sugar) + getQMC(Item.egg) + getQMC(Block.pumpkin));
    
    add(Item.record13, 8192);
    add(Item.recordCat, getQMC(Item.record11));
    add(Item.recordBlocks, getQMC(Item.record11));
    add(Item.recordChirp, getQMC(Item.record11));
    add(Item.recordFar, getQMC(Item.record11));
    add(Item.recordMall, getQMC(Item.record11));
    add(Item.recordMellohi, getQMC(Item.record11));
    add(Item.recordStal, getQMC(Item.record11));
    add(Item.recordStrad, getQMC(Item.record11));
    add(Item.recordWard, getQMC(Item.record11));
    add(Item.record11, getQMC(Item.record11));
    add(Item.recordWait, getQMC(Item.record11));
    
    add(Item.helmetLeather, 0, getQMC(Item.leather) * 5);
    add(Item.plateLeather, 0, getQMC(Item.leather) * 8);
    add(Item.legsLeather, 0, getQMC(Item.leather) * 7);
    add(Item.bootsLeather, 0, getQMC(Item.leather) * 4);
    add(Item.helmetIron, 0, getQMC(Item.ingotIron) * 5);
    add(Item.plateIron, 0, getQMC(Item.ingotIron) * 8);
    add(Item.legsIron, 0, getQMC(Item.ingotIron) * 7);
    add(Item.bootsIron, 0, getQMC(Item.ingotIron) * 4);
    add(Item.helmetGold, 0, getQMC(Item.ingotGold) * 5);
    add(Item.plateGold, 0, getQMC(Item.ingotGold) * 8);
    add(Item.legsGold, 0, getQMC(Item.ingotGold) * 7);
    add(Item.bootsGold, 0, getQMC(Item.ingotGold) * 4);
    add(Item.helmetDiamond, 0, getQMC(Item.diamond) * 5);
    add(Item.plateDiamond, 0, getQMC(Item.diamond) * 8);
    add(Item.legsDiamond, 0, getQMC(Item.diamond) * 7);
    add(Item.bootsDiamond, 0, getQMC(Item.diamond) * 4);
    
    int reg = length() - r;
    Log.info(reg + " Minecraft " + nameFull + " Values Loaded");
  }
}
