package oe.value;

import oe.Log;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class MinecraftValues extends Values {
  public static void load() {
    
    int r = Length();
    
    add(Block.cobblestone, 1);
    add(Block.stone, 1);
    add(Block.dirt, 1);
    add(Block.gravel, 1);
    add(Block.grass, 1);
    add(Block.mycelium, 8);
    add(Block.sand, 1);
    add(Item.diamond, 8192);
    add(Item.ingotGold, 2048);
    add(Item.ingotIron, 256);
    add(Block.sapling, 8);
    add(Block.leaves, 1);
    add(Block.wood, 32);
    add(Item.dyePowder, 4, 512);
    add(Item.dyePowder, 8);
    add(Block.plantRed, 8);
    add(Block.plantYellow, 8);
    add(Item.glowstone, 64);
    add(Item.slimeBall, 64);
    add(Item.clay, 32);
    add(Block.web, 8);
    add(Block.tallGrass, 8);
    add(Block.deadBush, 8);
    add(Block.mushroomBrown, 4);
    add(Block.mushroomRed, 4);
    add(Block.cloth, 48); // Wool
    add(Item.gunpowder, 256);
    add(Item.coal, 0, 128); // Coal
    add(Item.coal, 1, 32); // Charcoal
    add(Block.cobblestoneMossy, 128);
    add(Item.leather, 12);
    add(Block.reed, 16);
    add(Item.reed, 16);
    add(Item.wheat, 24);
    add(Item.carrot, 24);
    add(Item.potato, 24);
    add(Item.poisonousPotato, 12);
    add(Item.bakedPotato, 24);
    add(Block.carrot, 12);
    add(Block.potato, 12);
    add(Block.obsidian, 128);
    add(Item.redstone, 64);
    add(Item.snowball, 1);
    add(Block.ice, 16);
    add(Block.cactus, 8);
    add(Item.clay, 8);
    add(Block.pumpkin, 64);
    add(Item.pumpkinSeeds, 16);
    add(Item.melon, 12);
    add(Block.melon, 108);
    add(Block.netherrack, 1);
    add(Block.slowSand, 4);
    add(Item.glowstone, 64);
    add(Item.egg, 32);
    add(Block.vine, 16);
    add(Block.waterlily, 16);
    add(Block.netherBrick, 4);
    add(Block.netherStalk, 32);
    add(Block.whiteStone, 8);
    add(Item.enderPearl, 1024);
    add(Item.blazeRod, 512);
    add(Item.emerald, 16384);
    add(Item.netherQuartz, 512);
    add(Block.cocoaPlant, 24);
    add(Item.flint, 1);
    add(Item.feather, 12);
    add(Item.chickenRaw, 12);
    add(Item.feather, 12);
    add(Item.beefRaw, 32);
    add(Item.porkRaw, 32);
    add(Item.bone, 12);
    add(Item.rottenFlesh, 12);
    add(Item.ghastTear, 2048);
    add(Item.spiderEye, 12);
    add(Item.fishRaw, 32);
    
    add(Block.planks, getValue(Block.wood) / 4);
    add(Item.stick, getValue(Block.planks) / 2);
    add(Block.glass, getValue(Block.sand));
    add(Block.blockIron, getValue(Item.ingotIron) * 9);
    add(Block.blockGold, getValue(Item.ingotGold) * 9);
    add(Block.blockDiamond, getValue(Item.diamond) * 9);
    add(Block.blockLapis, getValue(new ItemStack(Item.dyePowder, 1, 4)) * 9);
    add(Block.blockEmerald, getValue(Item.emerald) * 9);
    add(Block.blockNetherQuartz, getValue(Item.netherQuartz) * 9);
    add(Block.blockRedstone, getValue(Item.redstone) * 9);
    add(Item.netherStar, getValue(Item.diamond) * 64);
    add(Item.brick, getValue(Item.clay));
    add(Block.coalBlock, getValue(Item.coal) * 9);
    add(Block.tripWire, getValue(Block.cloth) / 4);
    add(Item.bow, (getValue(Item.stick) * 3) + (getValue(Block.tripWire) * 3));
    add(Block.dispenser, (getValue(Block.cobblestone) * 7) + getValue(Item.bow) + getValue(Item.redstone));
    add(Block.torchRedstoneActive, getValue(Item.stick) + getValue(Item.redstone));
    add(Block.torchRedstoneIdle, getValue(Block.torchRedstoneActive));
    add(Block.railPowered, ((getValue(Item.ingotGold) * 6) + getValue(Item.redstone) + getValue(Item.stick)) / 6);
    add(Block.railDetector, ((getValue(Item.ingotGold) * 6) + getValue(Item.redstone) + getValue(Block.pressurePlateStone)) / 6);
    add(Block.rail, ((getValue(Item.ingotIron) * 6) + getValue(Item.stick)) / 16);
    add(Block.railActivator, ((getValue(Item.ingotIron) * 6) + getValue(Block.torchRedstoneActive) + ((getValue(Item.stick) * 2))) / 6);
    add(Block.pistonBase, (getValue(Block.wood) * 3) + (getValue(Block.cobblestone) * 4) + getValue(Item.ingotIron) + getValue(Item.redstone));
    add(Block.pistonStickyBase, getValue(Block.pistonBase) + getValue(Item.slimeBall));
    add(Block.brick, getValue(Item.brick) * 4);
    add(Block.sandStone, getValue(Block.sand) * 4);
    add(Block.music, (getValue(Block.wood) * 8) + getValue(Item.redstone));
    add(Block.tnt, (getValue(Block.sand) * 4) + (getValue(Item.gunpowder) * 5));
    add(Block.torchWood, (getValue(Item.stick) + getValue(new ItemStack(Item.coal, 1, 1))) / 4);
    add(Item.bed, (getValue(Block.wood) * 3) + (getValue(Block.cloth) * 3));
    add(Item.blazePowder, getValue(Item.blazeRod) / 5);
    add(Item.magmaCream, getValue(Item.blazePowder) + getValue(Item.slimeBall));
    add(Item.chickenCooked, getValue(Item.chickenRaw));
    add(Item.beefCooked, getValue(Item.beefRaw));
    add(Item.porkCooked, getValue(Item.porkRaw));
    add(Item.fishCooked, getValue(Item.fishRaw));
    add(Item.bread, getValue(Item.wheat) * 3);
    add(Item.seeds, getValue(Item.wheat));
    add(Item.sugar, getValue(Item.reed));
    add(Item.paper, getValue(Item.reed));
    add(Item.book, (getValue(Item.paper) * 3) + getValue(Item.leather));
    add(Block.bookShelf, (getValue(Item.book) * 3) + (getValue(Block.wood) * 6));
    add(Block.stairsWoodBirch, (getValue(Block.wood) * 6) / 4);
    add(Block.stairsWoodJungle, (getValue(Block.wood) * 6) / 4);
    add(Block.stairsWoodOak, (getValue(Block.wood) * 6) / 4);
    add(Block.stairsWoodSpruce, (getValue(Block.wood) * 6) / 4);
    add(Block.chest, getValue(Block.wood) * 8);
    add(Block.workbench, getValue(Block.wood) * 4);
    add(Block.furnaceIdle, getValue(Block.cobblestone) * 8);
    add(Block.signPost, ((getValue(Block.wood) * 6) + getValue(Item.stick)) / 3);
    add(Block.signWall, getValue(Block.signPost));
    add(Item.sign, getValue(Block.signPost));
    add(Block.doorWood, getValue(Block.wood) * 6);
    add(Item.doorWood, getValue(Block.wood) * 6);
    add(Block.doorIron, getValue(Item.ingotIron) * 6);
    add(Item.doorIron, getValue(Item.ingotIron) * 6);
    add(Block.ladder, (getValue(Item.stick) * 6) / 2);
    add(Block.lever, getValue(Item.stick) + getValue(Block.cobblestone));
    add(Block.pressurePlateStone, getValue(Block.stone) * 2);
    add(Block.pressurePlatePlanks, getValue(Block.planks) * 2);
    add(Block.stoneButton, getValue(Block.cobblestone) * 2);
    add(Block.woodenButton, getValue(Block.planks) * 2);
    add(Block.snow, getValue(Item.snowball) * 4);
    add(Block.blockClay, getValue(Item.clay) * 4);
    add(Block.jukebox, (getValue(Block.planks) * 8) + getValue(Item.redstone));
    add(Block.fence, (getValue(Item.stick) * 6) / 2);
    add(Block.glowStone, getValue(Item.glowstone) * 4);
    add(Item.bucketEmpty, getValue(Item.ingotIron) * 3);
    add(Item.bucketMilk, (getValue(Item.ingotIron) * 3) + 32);
    add(Item.bucketWater, (getValue(Item.ingotIron) * 3) + 2);
    add(Item.bucketLava, (getValue(Item.ingotIron) * 3) + 16);
    add(Block.cake, ((getValue(Item.bucketMilk) - getValue(Item.bucketEmpty)) * 3) + ((getValue(Item.sugar) * 2) + getValue(Item.egg)) + (getValue(Item.wheat) * 3));
    add(Item.cake, getValue(Block.cake));
    add(Item.redstoneRepeater, (getValue(Block.torchRedstoneActive) * 2) + getValue(Item.redstone) + (getValue(Block.stone) * 3));
    add(Block.redstoneRepeaterActive, getValue(Item.redstoneRepeater));
    add(Block.redstoneRepeaterIdle, getValue(Item.redstoneRepeater));
    add(Block.tripWireSource, getValue(Item.ingotIron) + getValue(Item.stick) + getValue(Block.planks));
    add(Block.chestTrapped, getValue(Block.chest) + getValue(Block.tripWireSource));
    add(Block.trapdoor, getValue(Block.planks) * 6 / 2);
    add(Block.stoneBrick, getValue(Block.stone) * 4);
    add(Block.fenceIron, getValue(Item.ingotIron) * 6 / 16);
    add(Block.thinGlass, getValue(Block.glass) * 6 / 16);
    add(Block.fenceGate, (getValue(Block.planks) * 2) + (getValue(Item.stick) * 4));
    add(Block.stairsBrick, getValue(Block.brick) * 6 / 4);
    add(Block.stairsStoneBrick, getValue(Block.stoneBrick) * 6 / 4);
    add(Block.stairsNetherQuartz, getValue(Block.blockNetherQuartz) * 6 / 4);
    add(Block.stairsCobblestone, getValue(Block.cobblestone) * 6 / 4);
    add(Block.netherFence, getValue(Block.netherBrick) * 6 / 6);
    add(Block.stairsNetherBrick, getValue(Block.netherBrick) * 6 / 4);
    add(Block.enchantmentTable, (getValue(Block.obsidian) * 4) + (getValue(Item.diamond) * 4) + getValue(Item.book));
    add(Block.cauldron, getValue(Item.ingotIron) * 7);
    add(Block.redstoneLampActive, getValue(Block.glowStone) + (getValue(Item.redstone) * 4));
    add(Block.redstoneLampIdle, getValue(Block.redstoneLampActive));
    add(Block.woodSingleSlab, getValue(Block.planks) * 3 / 6);
    add(Block.woodDoubleSlab, getValue(Block.woodSingleSlab) * 2);
    add(Block.stoneSingleSlab, 0, getValue(Block.stone) * 3 / 6);
    add(Block.stoneDoubleSlab, 0, getValue(new ItemStack(Block.stoneDoubleSlab, 1, 0)) * 2);
    add(Block.stoneSingleSlab, 1, getValue(Block.sandStone) * 3 / 6);
    add(Block.stoneDoubleSlab, 1, getValue(new ItemStack(Block.stoneDoubleSlab, 1, 1)) * 2);
    add(Block.stoneSingleSlab, 3, getValue(Block.cobblestone) * 3 / 6);
    add(Block.stoneDoubleSlab, 3, getValue(new ItemStack(Block.stoneDoubleSlab, 1, 3)) * 2);
    add(Block.stoneSingleSlab, 4, getValue(Block.brick) * 3 / 6);
    add(Block.stoneDoubleSlab, 4, getValue(new ItemStack(Block.stoneDoubleSlab, 1, 4)) * 2);
    add(Block.stoneSingleSlab, 5, getValue(Block.stoneBrick) * 3 / 6);
    add(Block.stoneDoubleSlab, 5, getValue(new ItemStack(Block.stoneDoubleSlab, 1, 5)) * 2);
    add(Block.stoneSingleSlab, 6, getValue(Block.netherBrick) * 3 / 6);
    add(Block.stoneDoubleSlab, 6, getValue(new ItemStack(Block.stoneDoubleSlab, 1, 6)) * 2);
    add(Block.stoneSingleSlab, 7, getValue(Block.blockNetherQuartz) * 3 / 6);
    add(Block.stoneDoubleSlab, 7, getValue(new ItemStack(Block.stoneDoubleSlab, 1, 7)) * 2);
    add(Item.eyeOfEnder, getValue(Item.enderPearl) + getValue(Item.blazePowder));
    add(Block.enderChest, (getValue(Block.obsidian) * 8) + getValue(Item.eyeOfEnder));
    add(Block.beacon, (getValue(Block.obsidian) * 3) + (getValue(Block.glass) * 5) + getValue(Item.netherStar));
    add(Block.cobblestoneWall, 0, getValue(Block.cobblestone) * 6 / 6);
    add(Block.cobblestoneWall, 1, getValue(Block.cobblestoneMossy) * 6 / 6);
    add(Block.flowerPot, getValue(Item.brick) * 3);
    add(Block.anvil, (getValue(Block.blockIron) * 3) + (getValue(Item.ingotIron) * 4));
    add(Block.pressurePlateGold, getValue(Item.ingotGold) * 2);
    add(Block.pressurePlateIron, getValue(Item.ingotIron) * 2);
    add(Block.redstoneComparatorActive, (getValue(Block.stone) * 3) + (getValue(Block.torchRedstoneActive) * 3) + getValue(Item.netherQuartz));
    add(Block.redstoneComparatorIdle, getValue(Block.redstoneComparatorActive));
    add(Item.comparator, getValue(Block.redstoneComparatorActive));
    add(Block.hopperBlock, (getValue(Item.ingotIron) * 5) + getValue(Block.chest));
    add(Block.dropper, (getValue(Block.cobblestone) * 7) + getValue(Item.redstone));
    add(Block.hardenedClay, getValue(Block.blockClay));
    add(Block.stainedClay, ((getValue(Block.hardenedClay) * 8) + getValue(Item.dyePowder)) / 8);
    add(Block.carpet, getValue(Block.cloth) * 2 / 3);
    add(Item.axeDiamond, 0, (getValue(Item.stick) * 2) + (getValue(Item.diamond) * 3));
    add(Item.pickaxeDiamond, 0, (getValue(Item.stick) * 2) + (getValue(Item.diamond) * 3));
    add(Item.shovelDiamond, 0, (getValue(Item.stick) * 2) + (getValue(Item.diamond) * 1));
    add(Item.swordDiamond, 0, (getValue(Item.stick) * 2) + (getValue(Item.diamond) * 2));
    add(Item.axeGold, 0, (getValue(Item.stick) * 2) + (getValue(Item.ingotGold) * 3));
    add(Item.pickaxeGold, 0, (getValue(Item.stick) * 2) + (getValue(Item.ingotGold) * 3));
    add(Item.shovelGold, 0, (getValue(Item.stick) * 2) + (getValue(Item.ingotGold) * 1));
    add(Item.swordGold, 0, (getValue(Item.stick) * 2) + (getValue(Item.ingotGold) * 2));
    add(Item.axeIron, 0, (getValue(Item.stick) * 2) + (getValue(Item.ingotIron) * 3));
    add(Item.pickaxeIron, 0, (getValue(Item.stick) * 2) + (getValue(Item.ingotIron) * 3));
    add(Item.shovelIron, 0, (getValue(Item.stick) * 2) + (getValue(Item.ingotIron) * 1));
    add(Item.swordIron, 0, (getValue(Item.stick) * 2) + (getValue(Item.ingotIron) * 2));
    add(Item.axeStone, 0, (getValue(Item.stick) * 2) + (getValue(Block.cobblestone) * 3));
    add(Item.pickaxeStone, 0, (getValue(Item.stick) * 2) + (getValue(Block.cobblestone) * 3));
    add(Item.shovelStone, 0, (getValue(Item.stick) * 2) + (getValue(Block.cobblestone) * 1));
    add(Item.swordStone, 0, (getValue(Item.stick) * 2) + (getValue(Block.cobblestone) * 2));
    add(Item.bowlEmpty, getValue(Block.wood) * 3 / 4);
    add(Item.bowlEmpty, getValue(Item.bowlEmpty) + 16);
    add(Item.arrow, (getValue(Item.stick) + getValue(Item.flint) + getValue(Item.feather)) / 4);
    add(Item.boat, getValue(Block.wood) * 5);
    add(Item.minecartEmpty, getValue(Item.ingotIron) * 5);
    add(Item.minecartCrate, getValue(Item.minecartEmpty) + getValue(Block.chest));
    add(Item.minecartPowered, getValue(Item.minecartEmpty) + getValue(Block.furnaceIdle));
    add(Item.minecartHopper, getValue(Item.minecartEmpty) + getValue(Block.hopperBlock));
    add(Item.minecartTnt, getValue(Item.minecartEmpty) + getValue(Block.tnt));
    add(Item.compass, getValue(Item.redstone) + (getValue(Item.ingotIron) * 4));
    add(Item.fishingRod, 0, (getValue(Item.stick) * 3) + (getValue(Block.tripWire) * 2));
    add(Item.pocketSundial, (getValue(Item.ingotGold) * 4) + getValue(Item.redstone));
    add(Item.cookie, ((getValue(Item.wheat) * 2) + getValue(Block.cocoaPlant)) / 8);
    add(Item.map, (getValue(Item.paper) * 8) + getValue(Item.compass));
    add(Item.glassBottle, getValue(Block.glass) * 3 / 3);
    add(Item.fermentedSpiderEye, getValue(Block.mushroomBrown) + getValue(Item.sugar) + getValue(Item.spiderEye));
    add(Item.speckledMelon, (getValue(Item.goldNugget) * 8) + getValue(Item.melon));
    add(Item.pumpkinPie, getValue(Item.sugar) + getValue(Item.egg) + getValue(Block.pumpkin));
    
    add(Item.record13, 8192);
    add(Item.recordCat, getValue(Item.record11));
    add(Item.recordBlocks, getValue(Item.record11));
    add(Item.recordChirp, getValue(Item.record11));
    add(Item.recordFar, getValue(Item.record11));
    add(Item.recordMall, getValue(Item.record11));
    add(Item.recordMellohi, getValue(Item.record11));
    add(Item.recordStal, getValue(Item.record11));
    add(Item.recordStrad, getValue(Item.record11));
    add(Item.recordWard, getValue(Item.record11));
    add(Item.record11, getValue(Item.record11));
    add(Item.recordWait, getValue(Item.record11));
    
    add(Item.helmetLeather, 0, getValue(Item.leather) * 5);
    add(Item.plateLeather, 0, getValue(Item.leather) * 8);
    add(Item.legsLeather, 0, getValue(Item.leather) * 7);
    add(Item.bootsLeather, 0, getValue(Item.leather) * 4);
    add(Item.helmetIron, 0, getValue(Item.ingotIron) * 5);
    add(Item.plateIron, 0, getValue(Item.ingotIron) * 8);
    add(Item.legsIron, 0, getValue(Item.ingotIron) * 7);
    add(Item.bootsIron, 0, getValue(Item.ingotIron) * 4);
    add(Item.helmetGold, 0, getValue(Item.ingotGold) * 5);
    add(Item.plateGold, 0, getValue(Item.ingotGold) * 8);
    add(Item.legsGold, 0, getValue(Item.ingotGold) * 7);
    add(Item.bootsGold, 0, getValue(Item.ingotGold) * 4);
    add(Item.helmetDiamond, 0, getValue(Item.diamond) * 5);
    add(Item.plateDiamond, 0, getValue(Item.diamond) * 8);
    add(Item.legsDiamond, 0, getValue(Item.diamond) * 7);
    add(Item.bootsDiamond, 0, getValue(Item.diamond) * 4);
    
    int reg = Length() - r;
    Log.info(reg + " Minecraft " + nameFull + " Values Loaded");
  }
}
